In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.model_selection import train_test_split
train_data_path = "/kaggle/input/competitions/home-data-for-ml-course/train.csv"
test_data_path = "/kaggle/input/competitions/home-data-for-ml-course/test.csv"
home_data=pd.read_csv(train_data_path)
y=home_data.SalePrice

In [2]:
features=['LotArea','YearBuilt','1stFlrSF','2ndFlrSF','FullBath','BedroomAbvGr','TotRmsAbvGrd']
X=home_data[features]
X.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
0,8450,2003,856,854,2,3,8
1,9600,1976,1262,0,2,3,6
2,11250,2001,920,866,2,3,6
3,9550,1915,961,756,1,3,7
4,14260,2000,1145,1053,2,4,9

In [3]:
train_X,val_X,train_y,val_y=train_test_split(X,y,random_state=1)
rf_model=RandomForestRegressor(random_state=1,n_estimators=500)
rf_model.fit(train_X,train_y)
rf_val_predictions=rf_model.predict(val_X)
rf_val_mae=mean_absolute_error(rf_val_predictions,val_y)
rf_val_mse=np.sqrt(mean_squared_error(rf_val_predictions,val_y))

print("MAE:{:,.0f}".format(rf_val_mae))
print("MSE:{:,.0f}".format(rf_val_mse))

MAE:21,887
MSE:31,387

In [4]:
rf_model_on_full_data=RandomForestRegressor(random_state=1,n_estimators=500)
rf_model_on_full_data.fit(X,y)

RandomForestRegressor(n_estimators=500, random_state=1)

In [5]:
test_data=pd.read_csv(test_data_path)
test_X=test_data[features]
test_preds=rf_model_on_full_data.predict(test_X)

In [6]:
test_preds

array([122603.416, 154821.3  , 183365.37 , ..., 155641.286, 125810.   ,
       228505.47 ])

In [7]:
test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,ScreenPorch,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition
0,1461,20,RH,80.0,11622,Pave,NaN,Reg,Lvl,AllPub,...,120,0,NaN,MnPrv,NaN,0,6,2010,WD,Normal
1,1462,20,RL,81.0,14267,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,Gar2,12500,6,2010,WD,Normal
2,1463,60,RL,74.0,13830,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,MnPrv,NaN,0,3,2010,WD,Normal
3,1464,60,RL,78.0,9978,Pave,NaN,IR1,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2010,WD,Normal
4,1465,120,RL,43.0,5005,Pave,NaN,IR1,HLS,AllPub,...,144,0,NaN,NaN,NaN,0,1,2010,WD,Normal
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1454,2915,160,RM,21.0,1936,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,6,2006,WD,Normal
1455,2916,160,RM,21.0,1894,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,4,2006,WD,Abnorml
1456,2917,20,RL,160.0,20000,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,9,2006,WD,Abnorml
1457,2918,85,RL,62.0,10441,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,MnPrv,Shed,700,7,2006,WD,Normal
1458,2919,60,RL,74.0,9627,Pave,NaN,Reg,Lvl,AllPub,...,0,0,NaN,NaN,NaN,0,11,2006,WD,Normal

In [8]:
output=pd.DataFrame({'Id':test_data.Id,'SalePrice':test_preds})
output.to_csv('submission.csv',index=False)