In [1]:
import os
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error,mean_squared_error
from sklearn.model_selection import train_test_split
train_data_path = "/kaggle/input/competitions/home-data-for-ml-course/train.csv"
test_data_path = "/kaggle/input/competitions/home-data-for-ml-course/train.csv"
home_data=pd.read_csv(train_data_path)
y=home_data.SalePrice

In [2]:
features=['LotArea','YearBuilt','1stFlrSF','2ndFlrSF','FullBath','BedroomAbvGr','TotRmsAbvGrd']
X=home_data[features]
X.head()

,LotArea,YearBuilt,1stFlrSF,2ndFlrSF,FullBath,BedroomAbvGr,TotRmsAbvGrd
0,8450,2003,856,854,2,3,8
1,9600,1976,1262,0,2,3,6
2,11250,2001,920,866,2,3,6
3,9550,1915,961,756,1,3,7
4,14260,2000,1145,1053,2,4,9

In [3]:
train_X,val_X,train_y,val_y=train_test_split(X,y,random_state=1)
rf_model=RandomForestRegressor(random_state=1,n_estimators=500)
rf_model.fit(train_X,train_y)
rf_val_predictions=rf_model.predict(val_X)
rf_val_mae=mean_absolute_error(rf_val_predictions,val_y)
rf_val_mse=np.sqrt(mean_squared_error(rf_val_predictions,val_y))

print("MAE:{:,.0f}".format(rf_val_mae))
print("MSE:{:,.0f}".format(rf_val_mse))

MAE:21,887
MSE:31,387

In [4]:
rf_model_on_full_data=RandomForestRegressor(random_state=1,n_estimators=500)
rf_model_on_full_data.fit(X,y)

RandomForestRegressor(n_estimators=500, random_state=1)

In [5]:
test_data=pd.read_csv(test_data_path)
test_X=test_data[features]
test_preds=rf_model_on_full_data.predict(test_X)

In [6]:
test_preds

array([207558.3  , 175749.   , 219522.55 , ..., 244138.494, 135743.436,
       151541.1  ])

In [7]:
test_data

,Id,MSSubClass,MSZoning,LotFrontage,LotArea,Street,Alley,LotShape,LandContour,Utilities,...,PoolArea,PoolQC,Fence,MiscFeature,MiscVal,MoSold,YrSold,SaleType,SaleCondition,SalePrice
0,1,60,RL,65.0,8450,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2008,WD,Normal,208500
1,2,20,RL,80.0,9600,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,5,2007,WD,Normal,181500
2,3,60,RL,68.0,11250,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,9,2008,WD,Normal,223500
3,4,70,RL,60.0,9550,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,2,2006,WD,Abnorml,140000
4,5,60,RL,84.0,14260,Pave,NaN,IR1,Lvl,AllPub,...,0,NaN,NaN,NaN,0,12,2008,WD,Normal,250000
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1455,1456,60,RL,62.0,7917,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,8,2007,WD,Normal,175000
1456,1457,20,RL,85.0,13175,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,MnPrv,NaN,0,2,2010,WD,Normal,210000
1457,1458,70,RL,66.0,9042,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,GdPrv,Shed,2500,5,2010,WD,Normal,266500
1458,1459,20,RL,68.0,9717,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,4,2010,WD,Normal,142125
1459,1460,20,RL,75.0,9937,Pave,NaN,Reg,Lvl,AllPub,...,0,NaN,NaN,NaN,0,6,2008,WD,Normal,147500

In [8]:
output=pd.DataFrame({'Id':test_data.Id,'SalePrice':test_preds})
output.to_csv('submission.csv',index=False)